function name = filename_generate(directory, original, im_rotate, power, rate, ft_rotate, pca_count)
    name=strcat(directory,...
    original(1:8),...
    num2str(im_rotate, '%03d'),...
    num2str(power, '%02d'),...
    num2str(rate, '%02d'),...
    num2str(ft_rotate, '%02d'),...
    num2str(pca_count, '%02d'),...
    original(9:end));
end